from enum import IntEnum


class Exceptions(IntEnum):
    INVALID_OBJECT_ID = 10
    GET_NOT_FOUND = 100
    GET_BAD_REQUEST = 101
    GET_UNKNOWN = 199
    CREATE_BAD_REQUEST = 200
    CREATE_UNKNOWN = 299
    UPDATE_BAD_REQUEST = 300
    UPDATE_UNKNOWN = 399
    DELETE_BAD_REQUEST = 400
    DELETE_UNKNOWN = 499
